extends:
 - urls: ['https://github.com/hashdist/hashstack2.git']
   key: 'git:5042aeaaee9841575e56ad9f673ef1585c2f5a46'
   file: debian.yaml

packages:
  zlib:
  szlib:
  nose:
  launcher:
  hdf5:
  jinja2:
  distribute:
  python:
    use: host-python
  mpi:
    use: host-mpi
