extends:
 - urls: ['https://github.com/hashdist/hashstack2.git']
   key: 'git:369a73dadcd437be50f386f7c24d08edc0d4748f'
   profile: debian.yaml

packages:
  - zlib
  - szlib
  - python:
      use: host-python
  - numpy:
      use: host-numpy
  - nose
  - launcher
  - hdf5
  - mpi:
      use: host-mpi
