extends:
 - name: hashstack
   urls: ['https://github.com/hashdist/hashstack.git']
   key: 'git:e66475eb4a273c8a5b2c30bbeded8af66fdf3de3'
   file: debian.yaml

packages:
  zlib:
  szlib:
  nose:
  launcher:
  hdf5:
  jinja2:
  distribute:
  python:
    host: true
